# Generated by Django 4.2.13 on 2024-05-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("run", "Run"),
                            ("gym", "Gym"),
                            ("workout", "Workout"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="activities.trainingsession",
                    ),
                ),
                ("distance_meters", models.PositiveIntegerField()),
                ("duration_minutes", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=150)),
                ("sets", models.PositiveSmallIntegerField()),
                ("reps", models.PositiveSmallIntegerField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("additional_weight", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.trainingsession",
                    ),
                ),
            ],
        ),
    ]
